### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by iridakos**

### CODE REVIEW

**Review by diakopter — COMMENTED** [review]
technically it's not a typo, just a (slightly) whimsical, (slightly) archaic colloquialism 😜

**Comment by iridakos** [comment]
> technically it's not a typo, just a (slightly) whimsical, (slightly) archaic colloquialism

@diakopter So many unknown words, I guess you are right :smiley_cat:

**Comment by diakopter** [comment]
https://www.merriam-webster.com/dictionary/many%20a/an 🐱‍🚀

**Comment by iridakos** [comment]
That is brand new information

**Pull request closed without merging**
