### PR TITLE
Improve IDE mode to provide basic Emacs mode interaction

### PR DESCRIPTION
**Pull request by symbiont-arnaud-bailly**
This PR is a first step towards providing a usable emacs idris-mode, implementing basic protocol to load files.

* refactor REPLs to decouple result generation from output
* implement `GetOptions` command 
* implement basic loading commands and protocol
* implement `metavariables` correctly when there's no hole

next step would be to provide syntax highlighting.

### CODE REVIEW

**Comment by edwinb** [comment]
Great, I've been hoping someone would make a start on this, thanks! There seem to be some conflicts at the moment though, so I'll come back to this later (unless you get there first...).

**Comment by abailly** [comment]
I will rebase when the PR queue gets shallower :)
No urgency and besides I have deep questions on how to tackle highlighting.

Le sam. 7 déc. 2019 à 16:30, Edwin Brady <notifications@github.com> a
écrit :

**Comment by abailly** [comment]
@edwinb finally found the time to rebase this PR. Tests were failing locally because of #177

**Comment by edwinb** [comment]
Thanks for the update! I'll merge now.

**Pull request merged**
