### PR TITLE
Port code examples for chapters 13 and 14 from TypeDD book

### PR DESCRIPTION
**Pull request by ska80**
All code from chapters 13 and 14 now typechecks.

But there are still problems with the generated code (I tested with Chez backend):

``Vending.idr``:
```
$ idris2 Vending.idr 
     ____    __     _         ___                                           
    /  _/___/ /____(_)____   |__ \                                          
    / // __  / ___/ / ___/   __/ /     Version 0.0.0-555be19aa
  _/ // /_/ / /  / (__  )   / __/      https://www.idris-lang.org           
 /___/\__,_/_/  /_/____/   /____/                                           

Welcome to Idris 2.  Enjoy yourself!
1/1: Building Vending (Vending.idr)
Main> :exec main
Exception in vector-ref: () is not a vector
Main> 
```

and ``Hangman.idr``:
```
idris2 Hangman.idr
     ____    __     _         ___                                           
    /  _/___/ /____(_)____   |__ \                                          
    / // __  / ___/ / ___/   __/ /     Version 0.0.0-555be19aa
  _/ // /_/ / /  / (__  )   / __/      https://www.idris-lang.org           
 /___/\__,_/_/  /_/____/   /____/                                           

Welcome to Idris 2.  Enjoy yourself!
Main> :exec main

-------
6 guesses left 
Guess: t
Correct
Exception: incorrect number of arguments to #<procedure>
Main> 
```

### CODE REVIEW

**Comment by edwinb** [comment]
Great, thanks. I'll investigate the run time issue before merging though.

**Comment by edwinb** [comment]
Uh oh, looks like the quantity checker is not spotting that a function is using an erased argument in the `Vending` example. I wonder how that has happened. This is a "drop everything and fix it now" bug...

**Comment by ska80** [comment]
> Uh oh, looks like the quantity checker is not spotting that a function is using an erased argument in the `Vending` example. I wonder how that has happened. This is a "drop everything and fix it now" bug...

@edwinb with the latest fixes I confirm that ``Vending.idr`` and ``Hangman.idr`` run as expected.  Thanks!

**Comment by edwinb** [comment]
Great, now I just need to get the concurrency system working properly and we can complete the book! Cheers!

**Pull request merged**
