### PR TITLE
install target depend on all target

### PR DESCRIPTION
**Pull request by diakopter**

### CODE REVIEW

**Comment by edwinb** [comment]
I'm using the 'install' target to build and install the libraries without having to build the executable too. The 'idris2' target can be slow to build. So this would be a bit annoying for me. Is this necessary, or is there another way that doesn't break my usual workflow?

**Comment by melted** [comment]
I guess one could have

```
install: all install-libs

install-libs:
   <current stuff>
```

One reason to have the dependency is that install is a very common target, so people expect it to work like usual.

**Comment by diakopter** [comment]
edited to support both the install-libs workflow and the typical install behavior

**Comment by edwinb** [comment]
Seems reasonable, thanks!

**Pull request merged**
