### PR TITLE
Linearity annotation in std-lib

### PR DESCRIPTION
**Pull request by ohad**
Add linearity annotations to the prelude.
Since that affects line numbers, also update one test.

### CODE REVIEW

**Comment by edwinb** [comment]
Looks like I've messed up the line numbers with some other merges, but I think it is good to have these annotations accurate when we can. Thanks for that!

**Comment by LeifW** [comment]
Now that Nat, Int, and Integer have their Num.+ impls marked as linear - I'm wondering if we'd want Num.+ itself marked as linear? It seems for most kinds of things we'd call numbers, we'd want + to use both args. But maybe we want to leave it flexible?

**Comment by ohad** [comment]
I'm wary of restricting the _interface_ to be left-linear.
Do you have an example of which client code could rely on `Num.+` instances being left-liner?

**Comment by edwinb** [comment]
I'm a bit scared of changing the interface too, as things are. There are other possible ways of implementing plus even for Nat that might be linear in the right argument. I think we need to get a bit more experience with this...

**Pull request merged**
