### PR TITLE
use quotient on scheme backends

### PR DESCRIPTION
**Pull request by abailly**
We compile divisions of Integers to quotient instead of '/' and add some tests for numbers, as using `/` has the undesirable side-effect of producing a non integral number

### CODE REVIEW

**Comment by ziman** [comment]
Related <s>(and probably conflicting)</s>: https://github.com/edwinb/Idris2/pull/281

**Comment by ziman** [comment]
If you have a clue what's going on in https://github.com/edwinb/Idris2/pull/281#issuecomment-613673042 and how to fix it, that would be great.

**Comment by abailly** [comment]
@ziman  Ah, did not check that PR, sorry if this PR is conflicting. I will have a look

**Comment by ziman** [comment]
It's actually not conflicting, as far as I can tell! It actually fixes a related issue that my PR missed.

**Comment by edwinb** [comment]
Thanks!

**Pull request merged**
